window.HUB_CONTENT = {
  de: {
    meta_title: "Ping Zhou Consulting | Technische Beratung & Vertrieb",
    nav_about: "Über uns",
    nav_areas: "Geschäftsbereiche",
    nav_contact: "Kontakt",
    nav_home: "Startseite",
    back_home: "← Zurück zur Startseite",
    hero_title: "Technische Beratung & spezialisierter Vertrieb",
    hero_sub: "Ping Zhou Consulting verbindet ingenieurorientierte Beratung mit dem Vertrieb hochspezialisierter Produkte — für Industrie und Anwendungen mit klaren technischen Anforderungen.",
    about_title: "Über Ping Zhou Consulting",
    about_text: "Wir unterstützen Kunden in Europa mit fachlicher Beratung, Produktauswahl und Lieferkoordination. Unser Fokus liegt auf zuverlässigen technischen Lösungen, transparenten Daten und einer langfristigen Partnerschaft — nicht auf anonymem Handel.",
    areas_title: "Unsere Geschäftsbereiche",
    areas_intro: "Zwei klar getrennte Produktwelten — jeweils mit eigener Expertise, eigenen Daten und eigenem Ansprechpartner.",
    area1_tag: "B2B · Hochtemperatur · Industrie",
    area1_title: "Thermofeld-Materialien",
    area1_text: "Weichfilz, Hartfilz und C/C-Verbundwerkstoffe für Hochtemperaturofen: Isolation, Chargiergestelle und thermische Komponenten für Wärmebehandlung, PV, Halbleiter und SiC-Prozesse bis 3200 °C.",
    area1_cta: "Zum Bereich Thermofeld →",
    area2_tag: "Sport · Training · Robotik",
    area2_title: "Ping-Pong-Robotik",
    area2_text: "Lösungen für Tischtennis-Training und Roboteranwendungen — ein eigenständiger Produktbereich mit Fokus auf Bedienung, Leistung und Kundennutzen im Sport- und Trainingsumfeld.",
    area2_cta: "Zum Bereich Robotik →",
    trust_title: "Warum Kunden uns beauftragen",
    trust1_t: "Technische Tiefe",
    trust1_d: "Datenblätter, Kennwerte und anwendungsorientierte Beratung",
    trust2_t: "Europa-Nähe",
    trust2_d: "Ansässig in Deutschland, Kommunikation auf Deutsch und Englisch",
    trust3_t: "Klare Struktur",
    trust3_d: "Getrennte Produktbereiche statt unübersichtlichem Mischsortiment",
    trust4_t: "Direkter Kontakt",
    trust4_d: "Persönliche Anfrage statt anonymer Plattform",
    contact_title: "Kontakt",
    contact_text: "Für Anfragen zu Thermofeld-Materialien, Robotik oder allgemeiner Beratung:",
    contact_address: "St.-Charles-Ring 2/1, 71638 Ludwigsburg, Deutschland",
    footer: "Ping Zhou Consulting · St.-Charles-Ring 2/1 · 71638 Ludwigsburg · Deutschland",
    impressum: "Impressum",
    privacy: "Datenschutz",
    impressum_title: "Impressum",
    privacy_title: "Datenschutz",
    impressum_body: "<p><strong>Ping Zhou Consulting</strong><br>Geschäftsführer: Ping Zhou<br>St.-Charles-Ring 2/1<br>71638 Ludwigsburg<br>Deutschland</p><p>Telefon: +49 173 4680010<br>E-Mail: contact@zhou-consult.de<br>USt-IdNr.: DE234711240</p>",
    privacy_body: "<p>Bei Kontaktaufnahme per E-Mail oder über Produktbereichs-Formulare werden Ihre Angaben zur Bearbeitung der Anfrage verarbeitet. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO. Die Daten werden gelöscht, sobald die Anfrage abschließend bearbeitet ist.</p><p>Verantwortlich: Ping Zhou Consulting, St.-Charles-Ring 2/1, 71638 Ludwigsburg, contact@zhou-consult.de</p>",
    robot_title: "Ping-Pong-Robotik",
    robot_intro: "Produktbereich in Vorbereitung. Bitte kontaktieren Sie <a href=\"mailto:contact@zhou-consult.de\">contact@zhou-consult.de</a>.",
  },
  en: {
    meta_title: "Ping Zhou Consulting | Technical Consulting & Sales",
    nav_about: "About us",
    nav_areas: "Business areas",
    nav_contact: "Contact",
    nav_home: "Home",
    back_home: "← Back to home",
    hero_title: "Technical consulting & specialized sales",
    hero_sub: "Ping Zhou Consulting combines engineering-oriented consulting with the distribution of highly specialized products — for industry and applications with clear technical requirements.",
    about_title: "About Ping Zhou Consulting",
    about_text: "We support customers in Europe with expert consulting, product selection and supply coordination. Our focus is on reliable technical solutions, transparent data and long-term partnership — not anonymous trading.",
    areas_title: "Our business areas",
    areas_intro: "Two clearly separated product worlds — each with its own expertise, data and dedicated point of contact.",
    area1_tag: "B2B · High temperature · Industry",
    area1_title: "Thermal field materials",
    area1_text: "Soft felt, cured felt and C/C composites for high-temperature furnaces: insulation, charging racks and thermal components for heat treatment, PV, semiconductor and SiC processes up to 3200 °C.",
    area1_cta: "Go to thermal field area →",
    area2_tag: "Sport · Training · Robotics",
    area2_title: "Ping-pong robotics",
    area2_text: "Solutions for table tennis training and robotics applications — a dedicated product area focused on ease of use, performance and customer value in sports and training environments.",
    area2_cta: "Go to robotics area →",
    trust_title: "Why customers choose us",
    trust1_t: "Technical depth",
    trust1_d: "Datasheets, specifications and application-oriented consulting",
    trust2_t: "European presence",
    trust2_d: "Based in Germany, communication in German and English",
    trust3_t: "Clear structure",
    trust3_d: "Separate product areas instead of a confusing mixed portfolio",
    trust4_t: "Direct contact",
    trust4_d: "Personal inquiry instead of an anonymous platform",
    contact_title: "Contact",
    contact_text: "For inquiries regarding thermal field materials, robotics or general consulting:",
    contact_address: "St.-Charles-Ring 2/1, 71638 Ludwigsburg, Germany",
    footer: "Ping Zhou Consulting · St.-Charles-Ring 2/1 · 71638 Ludwigsburg · Germany",
    impressum: "Legal notice",
    privacy: "Privacy policy",
    impressum_title: "Legal notice",
    privacy_title: "Privacy policy",
    impressum_body: "<p><strong>Ping Zhou Consulting</strong><br>Managing Director: Ping Zhou<br>St.-Charles-Ring 2/1<br>71638 Ludwigsburg<br>Germany</p><p>Phone: +49 173 4680010<br>Email: contact@zhou-consult.de<br>VAT ID: DE234711240</p>",
    privacy_body: "<p>When contacting us by email or via product area forms, your details are processed to handle your inquiry. Legal basis: Art. 6 (1) lit. b GDPR. Data is deleted once the inquiry is fully processed.</p><p>Controller: Ping Zhou Consulting, St.-Charles-Ring 2/1, 71638 Ludwigsburg, contact@zhou-consult.de</p>",
    robot_title: "Ping-pong robotics",
    robot_intro: "Product area in preparation. Please contact <a href=\"mailto:contact@zhou-consult.de\">contact@zhou-consult.de</a>.",
  }
};
